In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
#From python list
arr=np.array([1,2,3,4,5])

#2D array(matrix)
arr_2d=np.array([[1,2,3],[4,5,6]])

#Using buit-in functions
zeros=np.zeros((3,4))  #3*4 array of zeros
ones=np.ones((2,3))    #2*3 array of ones
range_arr=np.arange(0,10,2) #[0,2,4,6,8]
linspace=np.linspace(0,1,5)  #5 evenly spaced values from 0 to 1
identity=np.eye(3)  #3*3 identity matrix
random_arr=np.random.rand(3,4) #Random values between 0 to 1

print(zeros)
print("----------")
print(ones)
print("----------")
print(range_arr)
print("----------")
print(linspace)
print("----------")
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
[[1. 1. 1.]
 [1. 1. 1.]]
----------
[0 2 4 6 8]
----------
[0.   0.25 0.5  0.75 1.  ]
----------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.array([[1,2,3,],[4,5,6]])
print(a.shape) #(2,3)2 rows,3 columns

(2, 3)


In [ ]:
import numpy as np

# Crop yields for 4 farms over 5 seasons(in tons)
crop_yields=np.array([
    [12.5,13.22,14.1,13.8,15.2], #Farm 1 - North Region
    [10.3,11.5,10.8,12.1,11.9], #Farm 2 - South Region
    [15.1,14.8,16.2,15.5,16.8], #Farm 3 - East Region
    [11.2,10.9,12.3,11.7,12.8] #farm 4 - West Region
])

print('Crop Yields Array(tons):')
print(crop_yields)
print(f'\nShape:{crop_yields.shape}')
print(f'Data type:{crop_yields.dtype}')
print(f'Total elements:{crop_yields.size}')
print(f'Number of dimensions:{crop_yields.ndim}')

#Agricultural analysis operations
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\nTotal production:{total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons')
print(f'Maximum yield:{max_yield}tons')
print(f'Minimum yield:{min_yield}tons')


#Find best performing farm
best_farm=np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm:{best_farm+1}')
print(f'Their average yield:{avg_yield_per_farm[best_farm]:.2f}tons')


Crop Yields Array(tons):
[[12.5  13.22 14.1  13.8  15.2 ]
 [10.3  11.5  10.8  12.1  11.9 ]
 [15.1  14.8  16.2  15.5  16.8 ]
 [11.2  10.9  12.3  11.7  12.8 ]]

Shape:(4, 5)
Data type:float64
Total elements:20
Number of dimensions:2

Total production:262.71999999999997tons
Average per farm:[13.764 11.32  15.68  11.78 ]tons
Average per season:[12.275 12.605 13.35  13.275 14.175]tons
Maximum yield:16.8tons
Minimum yield:10.3tons

Best performing farm:3
Their average yield:15.68tons


In [ ]:
import numpy as np

#Agricultural analysis operations
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\nTotal production:{total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons')
print(f'Maximum yield:{max_yield}tons')
print(f'Minimum yield:{min_yield}tons')


#Find best performing farm
best_farm=np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm:{best_farm+1}')
print(f'Their average yield:{avg_yield_per_farm[best_farm]:.2f}tons')





Total production:262.71999999999997tons
Average per farm:[13.764 11.32  15.68  11.78 ]tons
Average per season:[12.275 12.605 13.35  13.275 14.175]tons
Maximum yield:16.8tons
Minimum yield:10.3tons

Best performing farm:3
Their average yield:15.68tons


In [ ]:
import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
print(arr)
np.sort(arr)

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(arr)
array([1,2,3,4,5,6,7,8])

NameError: name 'array' is not defined

In [ ]:
#numpy.argsort
import numpy as np
x=np.array([3,1,2])
np.argsort(x)

array([1, 2, 0])